kind: pipeline
type: docker
name: CI

steps:
- name: unittest
  image: python:3.7.3-slim-stretch
  commands:
    - pip install -U pip
    - pip install -r requirements-dev.txt
    - make test

- name: lint
  image: python:3.7.3-slim-stretch
  commands:
    - pip install -U pip
    - pip install -r requirements-dev.txt
    - make check