kind: pipeline
type: docker
name: CI

steps:
- name: unittest
  image: python:3.7.4
  commands:
    - pip install -U pip
    - pip install -r requirements-dev.txt
    - make test

- name: lint
  image: python:3.7.3
  commands:
    - pip install -U pip
    - pip install -r requirements-dev.txt
    - make check

---
kind: pipeline
type: docker
name: CD

steps:
- name: build & publish
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: ash84/drone-python
    dockerfile: Dockerfile
    tags:
      - ${DRONE_COMMIT_SHA}
  when:
    branch:
      - master
